version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Zipping application for deployment"
      - zip -r ../build.zip .

artifacts:
  files:
    - '**/*'
  base-directory: .
